
const API_BASE = '/api';

// Utility: Format Currency
const formatCurrency = (val) => {
    if (val >= 1e12) return `$${(val / 1e12).toFixed(2)}T`;
    if (val >= 1e9) return `$${(val / 1e9).toFixed(2)}B`;
    return `$${val.toLocaleString()}`;
};

// glossary.js (Inline)
const FINANCE_TERMS = {
    'Market Cap': 'The total value of a company\'s shares of stock.',
    'GDP': 'Gross Domestic Product: Total value of goods/services produced in the US.',
    'Buffett Indicator': 'Total Stock Market Cap divided by GDP. >100% suggests overvaluation.',
    'P/E': 'Price-to-Earnings Ratio. Measures current share price relative to per-share earnings.',
    'P/E Ratio': 'Price-to-Earnings Ratio. Measures current share price relative to per-share earnings.',
    'Div Yield': 'Dividend Yield. Annual dividend payments divided by the stock price.',
    'ROE': 'Return on Equity. Measures a company\'s profitability relative to stockholder\'s equity.',
    'Debt/Eq': 'Debt-to-Equity Ratio. Measures a company\'s financial leverage and risk.',
    'Profit Margin': 'Net Income divided by Revenue. Percentage of revenue kept as profit.',
    'Intrinsic Value': 'The calculated "true" value of a stock based on its future cash flows (DCF Model).',
    '5-Year Target': 'Projected stock price in 5 years assuming historical growth rates persist.',
    'Est. Growth': 'Estimated annual earnings growth rate based on historical trends.',
    'PEG': 'Price/Earnings-to-Growth. < 1.0 is considered undervalued.',
    'PEG Ratio': 'Price/Earnings-to-Growth. < 1.0 is considered undervalued.',
    'Proj. Growth': 'Projected Earnings Growth Rate.',
    'EV / EBITDA': 'Enterprise Value to EBITDA. A valuation multiple used to gauge if a company is cheap.',
    'EV/EBITDA': 'Enterprise Value to EBITDA. A valuation multiple used to gauge if a company is cheap.',
    'Free Cash Flow': 'Cash generated by the company after accounting for capital expenditures.',
    'Short Interest': 'Percentage of shares that have been sold short (betting on price drop).',
    'PUT OPTIONS': 'Financial contracts that give the owner the right to SELL a stock at a set price. A bet that price will DROP.',
    'CALL OPTIONS': 'Financial contracts that give the owner the right to BUY a stock at a set price. A bet that price will RISE.',
    'MACRO SHORT': 'A strategic bet against a broad economic trend or sector (e.g., betting against the AI bubble).',
    'ARBITRAGE': 'Profiting from price differences of the same asset in different markets (e.g., Merger Arb).',
    'DEEP VALUE': 'Buying stocks that are trading significantly below their intrinsic value, often distressed companies.',
    'OFFSHORE': 'Investing in companies that operate oil rigs at sea. Cyclical and capital intensive.',
    'ANTI-ESG': 'Investing in sectors like Coal/Oil/Tobacco that are shunned by Environmental, Social, and Governance funds.'
};

const renderWithTooltip = (label, termKey = null) => {
    const key = termKey || label;
    const def = FINANCE_TERMS[key];
    if (!def) return label;

    return `
        <span class="group relative inline-flex items-center gap-1 cursor-help">
            <span class="border-b border-dotted border-gray-500 group-hover:border-warren-accent transition-colors">${label}</span>
            <!-- Tooltip -->
            <div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-48 p-3 bg-gray-900 text-xs text-gray-300 rounded-lg shadow-[0_0_15px_rgba(0,0,0,0.5)] border border-gray-700 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50 text-center leading-relaxed">
                ${def}
                <div class="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 bg-gray-900 border-r border-b border-gray-700 transform rotate-45"></div>
            </div>
        </span>
    `;
};

const renderMetricWithContext = (label, value, contextValue, unit = '') => {
    // Renders the label with definition tooltip (existing) AND the value with context tooltip
    const labelHtml = renderWithTooltip(label);

    if (contextValue === undefined || contextValue === null) return `<div class="flex justify-between items-center text-sm"><span class="text-gray-500">${labelHtml}</span><span class="text-gray-200 font-mono">${value}${unit}</span></div>`;

    let diff = parseFloat(value) - parseFloat(contextValue);
    let comparisonText = diff > 0 ? 'Higher than avg' : 'Lower than avg';
    let comparisonColor = diff > 0 ? 'text-warren-warning' : 'text-warren-success';
    // Logic: Usually lower P/E, Debt is better (Green), Higher is warning? Or simplistic. 
    // Let's keep color neutral-ish or context aware. 
    // For MVP, just show text.

    return `
    <div class="flex justify-between items-center text-sm">
        <span class="text-gray-500">${labelHtml}</span>
        
        <!-- Value with Context Tooltip Wrapper -->
        <span class="relative group cursor-help">
            <span class="text-gray-200 font-mono border-b border-dotted border-gray-600 group-hover:border-warren-accent transition-colors">${value}${unit}</span>
            
            <!-- Context Tooltip (Left aligned to value) -->
            <div class="absolute bottom-full right-0 mb-2 w-48 p-3 bg-gray-900 ring-1 ring-white/10 text-xs text-gray-300 rounded-lg shadow-2xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50 text-right">
                <div class="text-[10px] uppercase tracking-wider text-gray-500 font-bold mb-1">Industry Standard</div>
                <div class="flex justify-end items-baseline gap-2">
                    <span class="text-white font-mono font-bold text-sm">${contextValue}${unit}</span>
                    <span class="text-[10px] text-gray-400">Avg</span>
                </div>
                <div class="mt-1 pt-1 border-t border-gray-800 text-[10px] ${comparisonColor}">
                    ${comparisonText}
                </div>
                <!-- Arrow -->
                <div class="absolute -bottom-1 right-3 w-2 h-2 bg-gray-900 border-r border-b border-gray-700/50 transform rotate-45"></div>
            </div>
        </span>
    </div>
    `;
};

// 1. Load Market Status
async function loadMarketStatus() {
    try {
        const res = await fetch(`${API_BASE}/market-status`);
        const data = await res.json();

        // Update DOM
        document.getElementById('buffett-ratio').textContent = `${data.ratio_percent}%`;
        document.getElementById('market-cap-val').textContent = formatCurrency(data.market_cap);
        document.getElementById('gdp-val').textContent = formatCurrency(data.gdp);

        const badge = document.getElementById('buffett-status-badge');
        badge.textContent = data.rating;

        // Detailed style for gauge
        let colorClass = 'bg-gray-500';
        let badgeColor = 'white';

        if (data.rating.includes('Undervalued')) {
            colorClass = 'bg-warren-success';
            badge.className = `text-xl font-semibold px-4 py-1 rounded-full bg-green-500/20 text-green-400`;
        } else if (data.rating.includes('Fair')) {
            colorClass = 'bg-warren-warning'; // Yellowish/Gold
            badge.className = `text-xl font-semibold px-4 py-1 rounded-full bg-yellow-500/20 text-yellow-400`;
        } else {
            colorClass = 'bg-warren-danger';
            badge.className = `text-xl font-semibold px-4 py-1 rounded-full bg-red-500/20 text-red-400`;
        }

        // Calculate Gauge Width (Clamp between 0 and 100% relative to a max of ~200%)
        // Let's say max logical range is 200%.
        const maxScale = 200;
        const widthPct = Math.min((data.ratio_percent / maxScale) * 100, 100);

        const gaugeFill = document.getElementById('gauge-fill');
        gaugeFill.style.width = `${widthPct}%`;
        // Remove existing bg classes and add new one
        gaugeFill.className = `h-full transition-all duration-1000 ease-out w-0 ${colorClass}`;

    } catch (err) {
        console.error("Failed to load market status", err);
    }
}

// Global Macro Data Store
let MACRO_DATA = null;

// 1.5 Load Macro Trends
async function loadMacroTrends() {
    try {
        const res = await fetch(`${API_BASE}/macro`);
        const data = await res.json();
        MACRO_DATA = data; // Store for table usage

        const container = document.getElementById('macro-container');
        container.innerHTML = '';

        const indicators = [
            { id: 'rates', label: '10Y Treasury', val: `${data.indicators.rates.current}%`, change: data.indicators.rates.change_pct, icon: 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6' },
            { id: 'oil', label: 'Crude Oil', val: `$${data.indicators.oil.current}`, change: data.indicators.oil.change_pct, icon: 'M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z' },
            { id: 'gold', label: 'Gold', val: `$${data.indicators.gold.current}`, change: data.indicators.gold.change_pct, icon: 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4' },
            { id: 'vix', label: 'VIX (Fear)', val: data.indicators.vix.current, change: data.indicators.vix.change_pct, icon: 'M13 10V3L4 14h7v7l9-11h-7z' },
        ];

        indicators.forEach(ind => {
            const isUp = ind.change > 0;
            // VIX/Rates UP is usually "Bad" (Red) for stocks, but let's stick to simple Green=Up, Red=Down for the indicator itself, 
            // OR color code by "Market Impact". Let's stick to neutral trend colors: Green=Up, Red=Down.
            const color = isUp ? 'text-green-400' : 'text-red-400';

            const div = document.createElement('div');
            div.className = "glass-panel p-4 rounded-xl flex flex-col justify-between";
            div.innerHTML = `
                <div class="flex justify-between items-start mb-2">
                    <span class="text-xs text-gray-400 uppercase">${ind.label}</span>
                    <svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="${ind.icon}"></path></svg>
                </div>
                <div>
                    <div class="text-xl font-mono text-white">${ind.val}</div>
                    <div class="text-xs ${color}">${isUp ? '+' : ''}${ind.change}% (5d)</div>
                </div>
            `;
            container.appendChild(div);
        });

    } catch (err) {
        console.error("Failed to load macro", err);
    }
}

// 2. Load Industries (Updated to use MACRO_DATA)
async function loadIndustries() {
    try {
        const res = await fetch(`${API_BASE}/industries/top`);
        const data = await res.json();

        const tbody = document.getElementById('industry-table-body');
        tbody.innerHTML = ''; // Clear loading

        data.forEach((ind, index) => {
            const tr = document.createElement('tr');
            tr.className = "hover:bg-gray-700/50 transition-colors group cursor-pointer";
            tr.onclick = () => loadStocks(ind.industry);

            // Macro Logic
            let macroHtml = '<span class="text-gray-600">-</span>';
            if (MACRO_DATA && MACRO_DATA.sector_impacts[ind.industry]) {
                const impact = MACRO_DATA.sector_impacts[ind.industry];
                if (impact.impact === 'Tailwind') {
                    macroHtml = `<div class="flex items-center gap-1 text-green-400 text-xs" title="${impact.reasons.join(', ')}">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"></path></svg>
                        Tailwind
                    </div>`;
                } else if (impact.impact === 'Headwind') {
                    macroHtml = `<div class="flex items-center gap-1 text-red-400 text-xs" title="${impact.reasons.join(', ')}">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 17h8m0 0V9m0 8l-8-8-4 4-6-6"></path></svg>
                        Headwind
                    </div>`;
                }
            }

            tr.innerHTML = `
                <td class="px-6 py-4 font-medium text-white group-hover:text-warren-accent transition-colors">
                    ${ind.industry}
                </td>
                <td class="px-6 py-4 text-gray-400">${ind.etf}</td>
                <td class="px-6 py-4">${macroHtml}</td>
                <td class="px-6 py-4">
                    <span class="${ind.pe < 20 ? 'text-green-400' : 'text-gray-300'}">${ind.pe}</span>
                </td>
                <td class="px-6 py-4 text-gray-300">${ind.dividend_yield}%</td>
                <td class="px-6 py-4 text-right">
                    <button class="text-xs bg-warren-accent/10 text-warren-accent px-3 py-1 rounded hover:bg-warren-accent hover:text-white transition-all">
                        Analyze
                    </button>
                </td>
            `;
            tbody.appendChild(tr);
        });

    } catch (err) {
        console.error("Failed to load industries", err);
    }
}

// 3. Load Stocks for an Industry
async function loadStocks(industryName) {
    const section = document.getElementById('stock-picks-section');
    const container = document.getElementById('stock-cards-container');
    const title = document.getElementById('selected-industry-name');
    const detailBody = document.getElementById('stock-detail-body');

    // Show section and scroll to it
    section.classList.remove('hidden');
    title.textContent = industryName;
    container.innerHTML = '<div class="col-span-full text-center py-10 text-gray-500 animate-pulse">Scanning Sector Fundamentals...</div>';

    section.scrollIntoView({ behavior: 'smooth' });

    try {
        const res = await fetch(`${API_BASE}/stocks/${encodeURIComponent(industryName)}`);
        const data = await res.json();

        // Clear loading
        container.innerHTML = '';
        detailBody.innerHTML = '';

        if (data.error) {
            container.innerHTML = `<div class="col-span-full text-center text-red-400 py-4">${data.error}</div>`;
            return;
        }

        // Add Cards for Top Picks
        data.top_stocks.forEach(stock => {
            const card = document.createElement('div');
            card.className = "glass-panel rounded-xl p-5 border-t-4 border-warren-accent hover:transform hover:-translate-y-1 transition-transform duration-300 relative overflow-hidden";

            // Innovation Score Bar
            const scoreWidth = stock.innovation_score;
            const scoreColor = scoreWidth > 80 ? 'bg-pink-500' : 'bg-blue-500';

            const tickerHtml = stock.symbol ? linkTV(stock.symbol) : '<span class="text-red-500">N/A</span>';

            card.innerHTML = `
                <div class="absolute top-0 left-0 w-1 h-full ${scoreColor} opacity-50"></div>
                <div class="flex justify-between items-start mb-2 pl-2">
                    <div>
                        <h4 class="font-bold text-white text-lg tracking-wide">${tickerHtml}</h4>
                        <div class="text-[10px] text-gray-400 uppercase tracking-wide">${stock.theme}</div>
                    </div>
                    <div class="text-right">
                        <div class="text-lg font-mono text-white">$${stock.price}</div>
                    </div>
                </div>
                
                <div class="space-y-1.5 mt-2">
                    ${renderMetricWithContext('P/E Ratio', stock.pe, data.avg_pe)}
                    ${renderMetricWithContext('ROE', stock.roe, data.avg_roe, '%')}
                    ${renderMetricWithContext('Debt/Eq', stock.debt_to_equity, data.avg_debt_equity)}
                </div>
                
                <div class="mt-3 pt-2 border-t border-gray-700/50 text-center">
                    <span class="text-[10px] uppercase tracking-wider text-warren-accent font-semibold flex items-center justify-center gap-1">
                        <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                        Analyst Approved
                    </span>
                </div>
            `;
            container.appendChild(card);
        });

        // Add Detail Rows
        data.all_analyzed.forEach(stock => {
            const isTop = data.top_stocks.find(t => t.symbol === stock.symbol);
            const tr = document.createElement('tr');
            tr.className = isTop ? "bg-warren-accent/5" : "text-gray-400";
            tr.innerHTML = `
                <td class="py-2 font-medium ${isTop ? 'text-white' : ''}">${linkTV(stock.symbol)}</td>
                <td class="py-2">$${stock.price}</td>
                <td class="py-2">${stock.pe}</td>
                <td class="py-2 ${stock.roe > 15 ? 'text-green-400' : ''}">${stock.roe}%</td>
                <td class="py-2">${stock.debt_to_equity}</td>
                <td class="py-2">${stock.profit_margin}%</td>
            `;
            detailBody.appendChild(tr);
        });

        // Render Matrix
        renderMoatMatrix(data.all_analyzed);

    } catch (err) {
        console.error("Failed to load stocks", err);
        container.innerHTML = `< div class="col-span-full text-center text-red-500" > Error loading stock data.</div > `;
    }
}

// 4. Search and Forecast
// 4. Search and Forecast
// 4. Search and Forecast
async function searchStock(symbol) {
    if (!symbol) return;

    const input = document.getElementById('stock-search');
    const strategySelect = document.getElementById('analyst-select');
    const strategyName = strategySelect.options[strategySelect.selectedIndex].text;
    const strategyValue = strategySelect.value;

    // Update Main Header Branding
    const brandName = strategyName.split(' ')[0] + (strategyValue === 'buffett' ? ' Indicator' : ' Analytics');
    const headerTitle = document.querySelector('header h1');
    if (headerTitle) {
        headerTitle.innerHTML = `${strategyName.split(' ')[0]} <span class="text-warren-accent">${strategyValue === 'buffett' ? 'Indicator' : 'Analytics'}</span>`;
    }

    const originalText = input.placeholder;
    input.disabled = true;
    input.value = `Asking ${strategyName}...`;

    try {
        const res = await fetch(`${API_BASE}/analyze/${encodeURIComponent(symbol)}?strategy=${strategyValue}`);
        const data = await res.json();

        if (data.error) {
            alert(data.error);
            input.value = "";
            input.disabled = false;
            return;
        }

        // Populate Modal
        const tickerSpan = document.getElementById('modal-ticker');
        const tvLink = document.getElementById('modal-tradingview-link');

        if (tickerSpan) {
            tickerSpan.textContent = data.symbol;
            console.log('Updated ticker span to:', data.symbol);
        }

        // Update TradingView link with proper URL
        if (tvLink) {
            const cleanSymbol = data.symbol.split(' ')[0].replace(/[^a-zA-Z]/g, '');
            const newHref = `https://www.tradingview.com/symbols/${cleanSymbol}/`;
            tvLink.href = newHref;
            console.log('Updated TradingView link to:', newHref);
        } else {
            console.error('TradingView link element not found!');
        }

        document.getElementById('modal-name').textContent = data.name;

        // Dynamic Analyst Header
        const verdictHeader = document.getElementById('modal-verdict-header');
        if (verdictHeader) {
            verdictHeader.textContent = `${strategyName.split(' ')[0]}'s Verdict`;
        }

        // Verdict styling
        const ratingEl = document.getElementById('modal-rating');
        ratingEl.textContent = data.rating;
        ratingEl.className = "text-xl font-bold";

        if (data.rating.includes('BUY') || data.rating.includes('Long')) ratingEl.classList.add('text-warren-success');
        else if (data.rating.includes('HOLD') || data.rating.includes('WATCH') || data.rating.includes('Pass')) ratingEl.classList.add('text-warren-warning');
        else ratingEl.classList.add('text-warren-danger');

        // Dynamic Main Metrics Grid (Intrinsic Value / Target / custom metrics)
        const metricsContainer = document.querySelector('#forecast-modal .grid.grid-cols-2');
        metricsContainer.innerHTML = ''; // Clear existing

        // Helper to add card
        const addCard = (label, value, colorClass = 'text-white') => {
            const el = document.createElement('div');
            el.className = 'bg-gray-800/50 p-4 rounded-xl text-center overflow-visible'; // overflow-visible for tooltip
            el.innerHTML = `
                <div class="text-xs text-gray-400 uppercase tracking-widest mb-1">${renderWithTooltip(label)}</div>
                <div class="text-2xl font-mono ${colorClass}">${value}</div>
            `;
            metricsContainer.appendChild(el);
        };

        // Strategy Specific Top Cards
        if (strategyValue === 'buffett') {
            const iv = data.intrinsic_value ? formatCurrency(data.intrinsic_value).replace('B', '').replace('T', '') : 'N/A';
            addCard('Intrinsic Value', iv);
            const target = data.target_price_5yr ? formatCurrency(data.target_price_5yr).replace('B', '').replace('T', '') : 'N/A';
            addCard('5-Year Target', target, 'text-warren-accent');

            // New Reverse DCF Card
            if (data.implied_growth_rate !== undefined) {
                const ig = data.implied_growth_rate;
                const igColor = ig > 15 ? 'text-warren-danger' : (ig < 5 ? 'text-warren-success' : 'text-yellow-400');
                addCard('Implied Growth', `${ig}%`, igColor);
            }

        } else if (strategyValue === 'lynch') {
            const peg = data.metrics && data.metrics.peg_ratio ? data.metrics.peg_ratio : 'N/A';
            addCard('PEG Ratio', peg, peg < 1.0 ? 'text-warren-success' : 'text-warren-warning');
            const growth = data.projected_growth_rate ? data.projected_growth_rate + '%' : 'N/A';
            addCard('Proj. Growth', growth, 'text-warren-accent');
        } else if (strategyValue === 'burry') {
            const evEbitda = data.metrics && data.metrics.ev_ebitda ? data.metrics.ev_ebitda : 'N/A';
            addCard('EV / EBITDA', evEbitda);
            const distress = data.metrics && data.metrics.debt_to_equity ? data.metrics.debt_to_equity : 'N/A';
            addCard('Debt/Equity', distress, parseFloat(distress) > 2 ? 'text-warren-danger' : 'text-white');
        }

        // Chart Visibility
        const chartContainer = document.getElementById('stock-price-chart').parentElement;
        if (data.target_price_5yr && data.target_price_5yr > 0) {
            chartContainer.classList.remove('hidden');
            setTimeout(() => {
                renderGrowthChart(data.symbol, data.current_price, data.target_price_5yr, strategyName);
            }, 100);
        } else {
            chartContainer.classList.add('hidden');
        }

        // Reasons
        const reasonsList = document.getElementById('modal-reasons');
        reasonsList.innerHTML = '';
        data.reasons.forEach(r => {
            const li = document.createElement('li');
            li.className = "flex items-start gap-2";
            li.innerHTML = `<span class="text-warren-accent mt-1">•</span> <span>${r}</span>`;
            reasonsList.appendChild(li);
        });

        // Bottom Footer Metrics (Dynamic based on strategy)
        const footerRow = document.querySelector('#forecast-modal .border-t.flex');
        footerRow.innerHTML = ''; // Clear default

        const addFooterItem = (label, val, color) => {
            const div = document.createElement('span');
            div.innerHTML = `${renderWithTooltip(label)}: <span class="${color || 'text-white'} ml-1">${val}</span>`;
            footerRow.appendChild(div);
        }

        const m = data.metrics || {};

        if (strategyValue === 'buffett') {
            addFooterItem('Est. Growth', data.projected_growth_rate ? `${data.projected_growth_rate}%` : '--', 'text-white');
            addFooterItem('ROE', m.roe ? `${m.roe}%` : '--', m.roe > 15 ? 'text-green-400' : 'text-white');
            addFooterItem('Debt/Eq', m.debt_to_equity || '--', 'text-white');
        } else if (strategyValue === 'lynch') {
            addFooterItem('PEG', m.peg_ratio || '--', m.peg_ratio < 1 ? 'text-green-400' : 'text-white');
            addFooterItem('Div Yield', m.dividend_yield ? `${m.dividend_yield}%` : '0%', 'text-white');
            addFooterItem('Debt/Eq', m.debt_to_equity || '--', 'text-white');
        } else if (strategyValue === 'burry') {
            addFooterItem('EV/EBITDA', m.ev_ebitda || '--', 'text-white');
            addFooterItem('Free Cash Flow', m.fcf_yield ? `${m.fcf_yield}%` : '--', 'text-blue-400');
            addFooterItem('Short Interest', m.short_float ? `${m.short_float}%` : '--', 'text-red-400');
        }


        // Show Modal
        document.getElementById('forecast-modal').classList.remove('hidden');

    } catch (err) {
        console.error("Analysis failed", err);
        alert("Failed to analyze stock.");
    } finally {
        input.value = "";
        input.placeholder = originalText;
        input.disabled = false;
    }
}

function renderGrowthChart(symbol, current, target, analystName) {
    const ctx = document.getElementById('stock-price-chart').getContext('2d');

    // Destroy previous instance if exists
    if (window.myStockChart) {
        window.myStockChart.destroy();
    }

    // Generate simple linear data points for 5 years
    const labels = ['Now', 'Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5'];
    const growth = (target - current) / 5;
    const dataPoints = Array.from({ length: 6 }, (_, i) => current + (growth * i));

    // Color logic
    const isPositive = target > current;
    const color = isPositive ? '#38bdf8' : '#ef4444'; // Blue or Red
    const bg = isPositive ? 'rgba(56, 189, 248, 0.1)' : 'rgba(239, 68, 68, 0.1)';

    window.myStockChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: `${symbol} ${analystName.split(' ')[0]} Projection`,
                data: dataPoints,
                borderColor: color,
                backgroundColor: bg,
                borderWidth: 2,
                fill: true,
                tension: 0.4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: true, labels: { color: '#9ca3af' } },
                tooltip: {
                    callbacks: {
                        label: function (context) {
                            return '$' + context.parsed.y.toFixed(2);
                        }
                    }
                }
            },
            scales: {
                y: {
                    grid: { color: 'rgba(75, 85, 99, 0.2)' },
                    ticks: { color: '#9ca3af', callback: (val) => '$' + val }
                },
                x: {
                    grid: { display: false },
                    ticks: { color: '#9ca3af' }
                }
            }
        }
    });
}


function renderMoatMatrix(stocks) {
    const canvas = document.getElementById('moat-matrix-chart');
    if (!canvas) return; // Guard clause

    const ctx = canvas.getContext('2d');

    // Destroy previous instance
    if (window.myMoatChart) {
        window.myMoatChart.destroy();
    }

    const dataPoints = stocks.map(s => ({
        x: s.profit_margin,
        y: s.roe,
        stock: s // Store full obj for tooltip
    }));

    window.myMoatChart = new Chart(ctx, {
        type: 'scatter',
        data: {
            datasets: [{
                label: 'Sector Stocks',
                data: dataPoints,
                backgroundColor: (ctx) => {
                    const v = ctx.raw;
                    if (!v) return 'rgba(156, 163, 175, 0.5)';
                    // Green if ROE > 15 and Margin > 15
                    if (v.y > 15 && v.x > 15) return 'rgba(34, 197, 94, 0.8)'; // Green
                    if (v.y < 5 || v.x < 5) return 'rgba(239, 68, 68, 0.8)'; // Red
                    return 'rgba(56, 189, 248, 0.6)'; // Blue default
                },
                borderColor: 'rgba(255,255,255,0.1)',
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                tooltip: {
                    callbacks: {
                        label: (ctx) => {
                            const p = ctx.raw;
                            return `${p.stock.symbol}: ROE ${p.y}% | Margin ${p.x}%`;
                        }
                    }
                },
                legend: { display: false }
            },
            scales: {
                x: {
                    title: { display: true, text: 'Profit Margin (%)', color: '#9ca3af' },
                    grid: { color: 'rgba(75, 85, 99, 0.2)' },
                    ticks: { color: '#9ca3af' }
                },
                y: {
                    title: { display: true, text: 'Return on Equity (ROE %)', color: '#9ca3af' },
                    grid: { color: 'rgba(75, 85, 99, 0.2)' },
                    ticks: { color: '#9ca3af' }
                }
            }
        }
    });
}

// Helper: TradingView Link
const linkTV = (symbol) => {
    // Handle special cases like "NVDA & PLTR" by splitting or just searching the first
    const cleanSymbol = symbol.split(' ')[0].replace(/[^a-zA-Z]/g, '');
    return `<a href="https://www.tradingview.com/symbols/${cleanSymbol}/" target="_blank" class="hover:text-warren-accent underline decoration-dotted transition-colors" title="View on TradingView">${symbol}</a>`;
};

// 5. Superinvestor Logic
async function loadSuperinvestors() {
    const container = document.getElementById('superinvestor-container');
    if (!container) return;

    // Check if already loaded to avoid refetching
    if (container.children.length > 0) return;

    try {
        const res = await fetch(`${API_BASE}/superinvestors`);
        const data = await res.json();

        container.innerHTML = '';

        data.forEach(investor => {
            const card = document.createElement('div');
            card.className = "glass-panel p-0 rounded-2xl border border-gray-700/50 hover:border-warren-accent/50 transition-all overflow-hidden flex flex-col";

            // Header
            card.innerHTML = `
                <div class="p-6 bg-gray-800/30 border-b border-gray-700">
                    <div class="flex items-center gap-4 mb-2">
                        <div class="w-12 h-12 rounded-full bg-gray-700 flex items-center justify-center text-xl font-bold text-white shadow-inner">
                            ${investor.name.split(' ').map(n => n[0]).join('')}
                        </div>
                        <div>
                            <h3 class="text-xl font-bold text-white">${investor.name}</h3>
                            <div class="text-xs text-gray-400">${investor.firm}</div>
                        </div>
                    </div>
                    <div class="mt-2 text-xs text-warren-accent font-medium uppercase tracking-wider">${investor.style}</div>
                </div>
                <div class="p-6 space-y-8 max-h-[500px] overflow-y-auto custom-scrollbar">
                    ${investor.history.map((quarter, idx) => {
                const isLatest = idx === 0;
                const buys = quarter.top_buys.map(b =>
                    `<div class="flex justify-between items-center text-sm mb-1"><span class="text-gray-300 tracking-wide font-medium">${b.name} (${linkTV(b.symbol)})</span> <span class="text-green-400 text-xs bg-green-400/10 px-2 py-0.5 rounded">${b.change}</span></div>`
                ).join('');

                const sells = quarter.top_sells.map(s =>
                    `<div class="flex justify-between items-center text-sm mb-1"><span class="text-gray-400 decoration-line-through">${s.name} (${linkTV(s.symbol)})</span> <span class="text-red-400 text-xs bg-red-400/10 px-2 py-0.5 rounded">${s.change}</span></div>`
                ).join('');

                const weird = quarter.weirdest_bet ? `
                             <div class="bg-gray-800/80 p-3 rounded-lg mt-3 border-l-2 border-purple-500">
                                <div class="flex justify-between items-center mb-1">
                                    <span class="font-bold text-white text-sm">${linkTV(quarter.weirdest_bet.symbol)}</span>
                                    <span class="text-[10px] uppercase text-purple-300 font-bold tracking-wider">${renderWithTooltip(quarter.weirdest_bet.type)}</span>
                                </div>
                                <p class="text-xs text-gray-400 leading-relaxed">"${quarter.weirdest_bet.description}"</p>
                             </div>
                        ` : '';

                return `
                            <div class="relative ${!isLatest ? 'opacity-80 hover:opacity-100 transition-opacity' : ''}">
                                ${!isLatest ? '<div class="absolute -left-3 top-2 bottom-0 w-0.5 bg-gray-700"></div>' : ''}
                                <div class="flex items-center gap-2 mb-3">
                                    <span class="text-sm font-bold ${isLatest ? 'text-white bg-warren-accent/20 px-2 py-1 rounded' : 'text-gray-500'}">${quarter.quarter}</span>
                                    ${isLatest ? '<span class="text-[10px] text-green-400 animate-pulse">● Latest</span>' : ''}
                                </div>
                                <p class="text-sm text-gray-400 italic mb-4">"${quarter.summary}"</p>
                                
                                <div class="space-y-4 pl-2">
                                    <div>
                                        <h4 class="text-[10px] uppercase text-gray-500 font-bold mb-2">Top Moves</h4>
                                        <div class="space-y-1">${buys}</div>
                                        <div class="space-y-1 mt-1">${sells}</div>
                                    </div>
                                    ${weird}
                                </div>
                            </div>
                            ${!isLatest && idx !== investor.history.length - 1 ? '<hr class="border-gray-700/50 my-6">' : ''}
                        `;
            }).join('<hr class="border-gray-700 my-6">')}
                </div>
            `;
            container.appendChild(card);
        });

    } catch (err) {
        console.error("Failed to load superinvestors", err);
    }
}

// 6. Copycat Portfolio Logic
async function loadCopycatPortfolio() {
    const tbody = document.getElementById('copycat-table-body');
    if (!tbody) return;

    // Only load if empty (prevent spamming API on tab switch)
    if (tbody.children.length > 0) return;

    tbody.innerHTML = '<tr><td colspan="6" class="px-6 py-8 text-center text-gray-500 animate-pulse">Fetching Real-Time Prices...</td></tr>';

    try {
        const res = await fetch(`${API_BASE}/copycat`);
        const data = await res.json();

        tbody.innerHTML = '';

        data.forEach(stock => {
            const tr = document.createElement('tr');
            tr.className = "hover:bg-gray-800/50 transition-colors";

            // Color logic
            const dailyColor = stock.daily_change >= 0 ? 'text-green-400' : 'text-red-400';
            const yearColor = stock.yearly_change >= 0 ? 'text-green-400' : 'text-red-400';
            const dailySign = stock.daily_change > 0 ? '+' : '';
            const yearSign = stock.yearly_change > 0 ? '+' : '';

            // Held By Badges
            const badges = stock.held_by.map(h => {
                let color = 'bg-gray-700 text-gray-300';
                if (h.includes('Buffett')) color = 'bg-blue-500/20 text-blue-300';
                if (h.includes('Burry')) color = 'bg-red-500/20 text-red-300';
                if (h.includes('Druckenmiller')) color = 'bg-yellow-500/20 text-yellow-300';
                if (h.includes('Pabrai')) color = 'bg-purple-500/20 text-purple-300';
                return `<span class="text-[10px] uppercase font-bold px-2 py-0.5 rounded ${color}">${h}</span>`;
            }).join(' ');

            tr.innerHTML = `
                <td class="px-6 py-4">
                    <div class="font-bold text-white">${linkTV(stock.symbol)}</div>
                    <div class="text-xs text-gray-500">${stock.name}</div>
                </td>
                <td class="px-6 py-4">
                    <div class="flex flex-wrap gap-1">${badges}</div>
                </td>
                <td class="px-6 py-4 text-right font-mono text-white">$${stock.price.toFixed(2)}</td>
                <td class="px-6 py-4 text-right font-mono ${dailyColor}">${dailySign}${stock.daily_change}%</td>
                <td class="px-6 py-4 text-right font-mono ${yearColor}">${yearSign}${stock.yearly_change}%</td>
                <td class="px-6 py-4 text-right">
                     <button onclick="searchStock('${stock.symbol}')" class="text-xs bg-warren-accent/10 text-warren-accent px-3 py-1 rounded hover:bg-warren-accent hover:text-white transition-all">
                        Analyze
                    </button>
                </td>
            `;
            tbody.appendChild(tr);
        });

    } catch (err) {
        console.error("Failed to load copycat", err);
        tbody.innerHTML = '<tr><td colspan="6" class="px-6 py-4 text-center text-red-400">Failed to load data.</td></tr>';
    }
}


// 7. Moonshot Logic
let MOONSHOT_STOCKS = []; // Store for local filtering

async function loadMoonshots() {
    const cols = {
        '3y': document.getElementById('moonshot-col-3y'),
        '5y': document.getElementById('moonshot-col-5y'),
        '10y': document.getElementById('moonshot-col-10y')
    };

    // Safety check
    if (!cols['3y']) return;

    // Only load once
    if (MOONSHOT_STOCKS.length > 0) return;

    // Loading state
    Object.values(cols).forEach(c => c.innerHTML = '<div class="text-center text-purple-400 animate-pulse text-xs">Scanning Future...</div>');

    try {
        const res = await fetch(`${API_BASE}/moonshots`);
        const data = await res.json();
        MOONSHOT_STOCKS = data;

        renderMoonshots(data); // Initial render
        setupMoonshotFilters();

    } catch (err) {
        console.error("Failed to load moonshots", err);
        Object.values(cols).forEach(c => c.innerHTML = '<div class="text-center text-red-400 text-xs">Signal Lost.</div>');
    }
}

function renderMoonshots(stocks) {
    const cols = {
        '3y': document.getElementById('moonshot-col-3y'),
        '5y': document.getElementById('moonshot-col-5y'),
        '10y': document.getElementById('moonshot-col-10y')
    };

    // Clear cols
    Object.values(cols).forEach(c => c.innerHTML = '');

    stocks.forEach(stock => {
        const targetCol = cols[stock.horizon];
        if (!targetCol) return;

        const card = document.createElement('div');
        // Cyberpunk styling
        card.className = "bg-gray-900/80 border border-gray-700 p-4 rounded-lg relative overflow-hidden group hover:border-purple-500/50 transition-all";

        // Exposure Badge Color
        const exposureColor = stock.role === 'Direct' ? 'bg-purple-500 text-white' : 'bg-gray-700 text-gray-400';

        // Innovation Score Bar
        const scoreWidth = stock.innovation_score;
        const scoreColor = scoreWidth > 80 ? 'bg-pink-500' : 'bg-blue-500';

        // Robust Ticker Logic
        const tickerHtml = stock.symbol ? linkTV(stock.symbol) : '<span class="text-red-500">N/A</span>';

        card.innerHTML = `
            <div class="absolute top-0 left-0 w-1 h-full ${scoreColor} opacity-50"></div>
            <div class="flex justify-between items-start mb-2 pl-2">
                <div>
                    <h4 class="font-bold text-white text-lg tracking-wide">${tickerHtml}</h4>
                    <div class="text-[10px] text-gray-400 uppercase tracking-wide">${stock.theme}</div>
                </div>
                <span class="text-[10px] uppercase font-bold px-2 py-0.5 rounded ${exposureColor}">${stock.role}</span>
            </div>
            
            <p class="text-xs text-gray-400 mb-3 leading-relaxed pl-2">
                ${stock.description}
            </p>
            
            <div class="flex justify-between items-center text-xs text-gray-500 pl-2">
                <span>$${stock.price}</span>
                <span class="${stock.change_pct >= 0 ? 'text-green-400' : 'text-red-400'}">${stock.change_pct > 0 ? '+' : ''}${stock.change_pct}%</span>
            </div>
            
            <!-- Innovation Score -->
            <div class="mt-3 pl-2">
                <div class="flex justify-between text-[10px] text-gray-500 mb-1">
                    <span>Innovation Score</span>
                    <span>${stock.innovation_score}/100</span>
                </div>
                <div class="h-1 w-full bg-gray-800 rounded-full overflow-hidden">
                    <div class="h-full ${scoreColor} rounded-full" style="width: ${scoreWidth}%"></div>
                </div>
            </div>
            
            <!-- Analyze Button overlay -->
            <button onclick="searchStock('${stock.symbol}')" class="absolute inset-0 w-full h-full opacity-0 hover:opacity-100 flex items-center justify-center bg-black/60 transition-opacity backdrop-blur-sm">
                <span class="bg-purple-600 text-white px-4 py-2 rounded-full font-bold shadow-[0_0_15px_rgba(168,85,247,0.5)] transform translate-y-4 group-hover:translate-y-0 transition-transform">
                    Analyze Deeply 🚀
                </span>
            </button>
        `;
        targetCol.appendChild(card);
    });
}

function setupMoonshotFilters() {
    const buttons = document.querySelectorAll('#moonshot-filters button');
    buttons.forEach(btn => {
        btn.onclick = () => {
            // Reset styles
            buttons.forEach(b => {
                b.className = "bg-gray-800 text-gray-400 hover:text-white px-3 py-1 rounded-full text-xs font-medium transition-colors cursor-pointer";
            });
            // Active style
            btn.className = "bg-purple-500/20 text-purple-300 border border-purple-500/50 px-3 py-1 rounded-full text-xs font-bold cursor-pointer";

            const theme = btn.getAttribute('data-theme');
            if (!theme) return;

            // Filter logic
            if (theme === 'all') {
                renderMoonshots(MOONSHOT_STOCKS);
            } else {
                // Fuzzy match or exact match
                const filtered = MOONSHOT_STOCKS.filter(s => s.theme.includes(theme) || theme === 'all');
                renderMoonshots(filtered);
            }
        }
    });
}



// 8. Screener Logic
async function runScreen(strategyId) {
    const tbody = document.getElementById('screener-table-body');
    const title = document.getElementById('screener-results-title');

    // UI Feedback
    tbody.innerHTML = '<tr><td colspan="4" class="px-6 py-8 text-center text-warren-accent animate-pulse">Running Strategy Scan... (This may take 10s)</td></tr>';

    // Map ID to readable name
    const names = {
        'magic_formula': 'Magic Formula 🪄',
        'rule_of_40': 'Rule of 40 🚀',
        'lynch': 'Peter Lynch Growth 📈',
        'deep_value': 'Deep Value 💎'
    };
    title.textContent = `Results: ${names[strategyId] || 'Custom Scan'}`;

    try {
        const res = await fetch(`${API_BASE}/screeners/${strategyId}`);
        const data = await res.json();

        tbody.innerHTML = '';

        if (data.length === 0) {
            tbody.innerHTML = '<tr><td colspan="4" class="px-6 py-8 text-center text-gray-400">No stocks in our universe matched this strict criteria.</td></tr>';
            return;
        }

        data.forEach(stock => {
            const tr = document.createElement('tr');
            tr.className = "hover:bg-gray-800/50 transition-colors border-b border-gray-800 last:border-0";
            tr.innerHTML = `
                <td class="px-6 py-4">
                    <div class="font-bold text-white text-lg">${linkTV(stock.symbol)}</div>
                    <div class="text-xs text-gray-500">${stock.name}</div>
                </td>
                <td class="px-6 py-4">
                    <span class="text-sm text-gray-300 font-medium">${stock.reason}</span>
                </td>
                <td class="px-6 py-4 text-right font-mono text-white">
                    $${stock.price}
                </td>
                <td class="px-6 py-4 text-right">
                    <button onclick="searchStock('${stock.symbol}')" class="text-xs bg-warren-accent/10 text-warren-accent px-3 py-1 rounded hover:bg-warren-accent hover:text-white transition-all">
                        Analyze
                    </button>
                </td>
            `;
            tbody.appendChild(tr);
        });

    } catch (err) {
        console.error("Screen failed", err);
        tbody.innerHTML = '<tr><td colspan="4" class="px-6 py-8 text-center text-red-400">Scan failed. Server may be busy.</td></tr>';
    }
}


// Tab Switching
// Tab Switching
window.switchTab = (tabName) => {
    // Buttons
    const btnDash = document.getElementById('tab-dashboard');
    const btnSuper = document.getElementById('tab-superinvestors');
    const btnCopy = document.getElementById('tab-copycat');
    const btnMoon = document.getElementById('tab-moonshots');
    const btnScreen = document.getElementById('tab-screeners');
    const btnEcon = document.getElementById('tab-economics');
    const btnNews = document.getElementById('tab-news');
    const btnPort = document.getElementById('tab-portfolio');

    // Views
    const viewDash = document.getElementById('dashboard-view');
    const viewSuper = document.getElementById('superinvestor-view');
    const viewCopy = document.getElementById('copycat-view');
    const viewMoon = document.getElementById('moonshot-view');
    const viewScreen = document.getElementById('screeners-view');
    const viewEcon = document.getElementById('economics-view');
    const viewNews = document.getElementById('news-view');
    const viewPort = document.getElementById('portfolio-view');

    // Reset All
    [btnDash, btnSuper, btnCopy, btnMoon, btnScreen, btnEcon, btnNews, btnPort].forEach(btn => {
        if (btn) {
            btn.classList.remove('bg-warren-accent', 'text-white', 'shadow-lg');
            btn.classList.add('text-gray-400');
        }
    });

    [viewDash, viewSuper, viewCopy, viewMoon, viewScreen, viewEcon, viewNews, viewPort].forEach(view => {
        if (view) view.classList.add('hidden');
    });

    // Activate Target
    if (tabName === 'dashboard') {
        btnDash.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnDash.classList.remove('text-gray-400');
        viewDash.classList.remove('hidden');
    } else if (tabName === 'superinvestors') {
        btnSuper.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnSuper.classList.remove('text-gray-400');
        viewSuper.classList.remove('hidden');
        loadSuperinvestors();
    } else if (tabName === 'copycat') {
        btnCopy.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnCopy.classList.remove('text-gray-400');
        viewCopy.classList.remove('hidden');
        loadCopycatPortfolio();
    } else if (tabName === 'moonshots') {
        btnMoon.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnMoon.classList.remove('text-gray-400');
        viewMoon.classList.remove('hidden');
        loadMoonshots();
    } else if (tabName === 'screeners') {
        btnScreen.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnScreen.classList.remove('text-gray-400');
        viewScreen.classList.remove('hidden');
    } else if (tabName === 'economics') {
        btnEcon.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnEcon.classList.remove('text-gray-400');
        viewEcon.classList.remove('hidden');
        loadEconomicIndicators();
    } else if (tabName === 'news') {
        btnNews.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnNews.classList.remove('text-gray-400');
        viewNews.classList.remove('hidden');
        loadMarketNews();
    } else if (tabName === 'portfolio') {
        btnPort.classList.add('bg-warren-accent', 'text-white', 'shadow-lg');
        btnPort.classList.remove('text-gray-400');
        viewPort.classList.remove('hidden');
        if (typeof initPortfolioView === 'function') {
            initPortfolioView();
        }
    }
}

// Economic Indicators
async function loadEconomicIndicators() {
    const grid = document.getElementById('indicators-grid');
    const source = document.getElementById('economics-source');

    grid.innerHTML = '<div class="col-span-full text-center text-warren-accent">Loading indicators...</div>';

    try {
        const res = await fetch(`${API_BASE}/economic-indicators`);
        const data = await res.json();

        source.textContent = `Source: ${data.source} | Last Updated: ${new Date(data.last_updated).toLocaleString()}`;

        const indicators = data.indicators;
        const labels = {
            'unemployment': { name: 'Unemployment Rate', unit: '%', goodTrend: 'down' },
            'inflation': { name: 'Inflation (CPI)', unit: '%', goodTrend: 'down' },
            'fed_rate': { name: 'Fed Funds Rate', unit: '%', goodTrend: 'stable' },
            'gdp_growth': { name: 'GDP Growth', unit: '%', goodTrend: 'up' }
        };

        grid.innerHTML = '';

        Object.keys(indicators).forEach(key => {
            const indicator = indicators[key];
            const label = labels[key];
            const monthChangeClass = indicator.month_change >= 0 ? 'text-red-400' : 'text-green-400';
            const trendIcon = indicator.trend;

            const card = document.createElement('div');
            card.className = 'glass-panel p-6 rounded-xl';
            card.innerHTML = `
                <div class="text-xs text-gray-400 uppercase tracking-wide mb-2">${label.name}</div>
                <div class="flex items-end justify-between">
                    <div>
                        <div class="text-3xl font-bold text-white">${indicator.value}${label.unit}</div>
                        <div class="${monthChangeClass} text-sm mt-1">
                            ${indicator.month_change > 0 ? '+' : ''}${indicator.month_change}${label.unit} (1M)
                        </div>
                    </div>
                    <div class="text-4xl opacity-50">${trendIcon}</div>
                </div>
                <div class="mt-3 text-xs text-gray-500">
                    YoY: ${indicator.year_change > 0 ? '+' : ''}${indicator.year_change}${label.unit}
                </div>
            `;
            grid.appendChild(card);
        });

    } catch (err) {
        console.error('Failed to load economic indicators', err);
        grid.innerHTML = '<div class="col-span-full text-center text-red-400">Failed to load indicators</div>';
    }
}

// Market News
async function loadMarketNews() {
    const feed = document.getElementById('news-feed');
    const source = document.getElementById('news-source');

    feed.innerHTML = '<div class="text-center text-warren-accent">Loading news...</div>';

    try {
        const res = await fetch(`${API_BASE}/news`);
        const data = await res.json();

        source.textContent = `Sources: ${data.sources.join(', ')} | Last Updated: ${new Date(data.last_updated).toLocaleString()}`;

        feed.innerHTML = '';

        data.news.forEach(item => {
            const newsCard = document.createElement('a');
            newsCard.href = item.link;
            newsCard.target = '_blank';
            newsCard.className = 'block glass-panel p-4 rounded-xl hover:border-warren-accent border border-transparent transition-all';
            newsCard.innerHTML = `
                <div class="flex justify-between items-start gap-4">
                    <div class="flex-1">
                        <h3 class="font-bold text-white mb-1 hover:text-warren-accent">${item.title}</h3>
                        ${item.summary ? `<p class="text-xs text-gray-400 line-clamp-2">${item.summary}</p>` : ''}
                    </div>
                    <div class="text-right flex-shrink-0">
                        <div class="text-xs text-gray-500">${item.published}</div>
                        <div class="text-xs text-gray-600 mt-1">${item.source}</div>
                    </div>
                </div>
            `;
            feed.appendChild(newsCard);
        });

    } catch (err) {
        console.error('Failed to load news', err);
        feed.innerHTML = '<div class="text-center text-red-400">Failed to load news</div>';
    }
}

function closeModal() {
    document.getElementById('forecast-modal').classList.add('hidden');
}

// Init
document.addEventListener('DOMContentLoaded', async () => {
    await loadMarketStatus();
    await loadMacroTrends(); // Load this first so we have data for the table
    await loadIndustries();
});
