"""
Dynamic Universe Updater
Fetches S&P 500 and Nasdaq 100 constituent lists from Wikipedia.
Run this script weekly or on-demand to keep the universe fresh.
"""

import pandas as pd
import os
from datetime import datetime

import requests
import io
from cache_utils import fetch_with_retry

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
}

def fetch_sp500_tickers():
    """Scrape S&P 500 tickers from Wikipedia."""
    try:
        url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
        response = fetch_with_retry(
            lambda: requests.get(url, headers=HEADERS, timeout=15),
            max_attempts=3,
            base_delay=2.0,
        )
        response.raise_for_status()
        
        tables = pd.read_html(io.StringIO(response.text))
        df = tables[0]  # First table contains the constituents
        tickers = df['Symbol'].tolist()
        # Clean up any special characters (e.g., BRK.B -> BRK-B for yfinance)
        tickers = [t.replace('.', '-') for t in tickers]
        return tickers
    except Exception as e:
        print(f"Error fetching S&P 500: {e}")
        return []

def fetch_nasdaq100_tickers():
    """Scrape Nasdaq 100 tickers from Wikipedia."""
    try:
        url = "https://en.wikipedia.org/wiki/Nasdaq-100"
        response = fetch_with_retry(
            lambda: requests.get(url, headers=HEADERS, timeout=15),
            max_attempts=3,
            base_delay=2.0,
        )
        response.raise_for_status()
        
        tables = pd.read_html(io.StringIO(response.text))
        # The constituents table is usually the 4th table (index 3)
        # Note: Wikipedia format changes often. We might need to hunt for the table.
        # Let's try to find the table with "Ticker" column.
        target_df = None
        for df in tables:
            if 'Ticker' in df.columns:
                target_df = df
                break
        
        if target_df is None:
            # Fallback to index 3 or 4 if auto-detection fails
            target_df = tables[3] if len(tables) > 3 else tables[0]
            
        tickers = target_df['Ticker'].tolist()
        return tickers
    except Exception as e:
        print(f"Error fetching Nasdaq 100: {e}")
        return []

def update_universe_file():
    """
    Fetches fresh ticker lists and updates universe.py.
    """
    print("Fetching S&P 500 constituents...")
    sp500 = fetch_sp500_tickers()
    
    print("Fetching Nasdaq 100 constituents...")
    nasdaq = fetch_nasdaq100_tickers()
    
    if not sp500 and not nasdaq:
        print("Failed to fetch any tickers. Aborting update.")
        return False
    
    # Generate the new universe.py content
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f'''# universe.py
# Auto-generated by updater.py on {timestamp}
# S&P 500 and Nasdaq 100 constituents

SP500_TOP = {sp500}

NASDAQ100_TOP = {nasdaq}

def get_master_universe():
    """
    Returns a deduplicated list of all major stocks.
    """
    unique_tickers = set(SP500_TOP + NASDAQ100_TOP)
    return list(unique_tickers)
'''
    
    # Write to file
    try:
        with open('universe.py', 'w') as f:
            f.write(content)
        print(f"✓ Updated universe.py with {len(sp500)} S&P 500 and {len(nasdaq)} Nasdaq 100 tickers.")
        print(f"  Total unique tickers: {len(set(sp500 + nasdaq))}")
        return True
    except Exception as e:
        print(f"Error writing universe.py: {e}")
        return False

if __name__ == "__main__":
    print("=== Dynamic Universe Updater ===")
    success = update_universe_file()
    if success:
        print("Universe update complete!")
    else:
        print("Universe update failed.")
