export const formatCurrency = (val) => {
    if (val >= 1e12) return `$${(val / 1e12).toFixed(2)}T`;
    if (val >= 1e9) return `$${(val / 1e9).toFixed(2)}B`;
    return `$${val.toLocaleString()}`;
};

export const FINANCE_TERMS = {
    'Market Cap': 'The total value of a company\'s shares of stock.',
    'GDP': 'Gross Domestic Product: Total value of goods/services produced in the US.',
    'Buffett Indicator': 'Total Stock Market Cap divided by GDP. >100% suggests overvaluation.',
    'P/E': 'Price-to-Earnings Ratio. Measures current share price relative to per-share earnings.',
    'P/E Ratio': 'Price-to-Earnings Ratio. Measures current share price relative to per-share earnings.',
    'Div Yield': 'Dividend Yield. Annual dividend payments divided by the stock price.',
    'ROE': 'Return on Equity. Measures a company\'s profitability relative to stockholder\'s equity.',
    'Debt/Eq': 'Debt-to-Equity Ratio. Measures a company\'s financial leverage and risk.',
    'Profit Margin': 'Net Income divided by Revenue. Percentage of revenue kept as profit.',
    'Intrinsic Value': 'The calculated "true" value of a stock based on its future cash flows (DCF Model).',
    '5-Year Target': 'Projected stock price in 5 years assuming historical growth rates persist.',
    'Est. Growth': 'Estimated annual earnings growth rate based on historical trends.',
    'PEG': 'Price/Earnings-to-Growth. < 1.0 is considered undervalued.',
    'PEG Ratio': 'Price/Earnings-to-Growth. < 1.0 is considered undervalued.',
    'Proj. Growth': 'Projected Earnings Growth Rate.',
    'EV / EBITDA': 'Enterprise Value to EBITDA. A valuation multiple used to gauge if a company is cheap.',
    'EV/EBITDA': 'Enterprise Value to EBITDA. A valuation multiple used to gauge if a company is cheap.',
    'Free Cash Flow': 'Cash generated by the company after accounting for capital expenditures.',
    'Short Interest': 'Percentage of shares that have been sold short (betting on price drop).',
    'PUT OPTIONS': 'Financial contracts that give the owner the right to SELL a stock at a set price. A bet that price will DROP.',
    'CALL OPTIONS': 'Financial contracts that give the owner the right to BUY a stock at a set price. A bet that price will RISE.',
    'MACRO SHORT': 'A strategic bet against a broad economic trend or sector (e.g., betting against the AI bubble).',
    'ARBITRAGE': 'Profiting from price differences of the same asset in different markets (e.g., Merger Arb).',
    'DEEP VALUE': 'Buying stocks that are trading significantly below their intrinsic value, often distressed companies.',
    'OFFSHORE': 'Investing in companies that operate oil rigs at sea. Cyclical and capital intensive.',
    'ANTI-ESG': 'Investing in sectors like Coal/Oil/Tobacco that are shunned by Environmental, Social, and Governance funds.'
};

export const renderWithTooltip = (label, termKey = null) => {
    const key = termKey || label;
    const def = FINANCE_TERMS[key];
    if (!def) return label;

    return `
        <span class="group relative inline-flex items-center gap-1 cursor-help">
            <span class="border-b border-dotted border-gray-500 group-hover:border-warren-accent transition-colors">${label}</span>
            <div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-48 p-3 bg-gray-900 text-xs text-gray-300 rounded-lg shadow-[0_0_15px_rgba(0,0,0,0.5)] border border-gray-700 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50 text-center leading-relaxed">
                ${def}
                <div class="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 bg-gray-900 border-r border-b border-gray-700 transform rotate-45"></div>
            </div>
        </span>
    `;
};

export const renderMetricWithContext = (label, value, contextValue, unit = '') => {
    const labelHtml = renderWithTooltip(label);

    if (contextValue === undefined || contextValue === null) return `<div class="flex justify-between items-center text-sm"><span class="text-gray-500">${labelHtml}</span><span class="text-gray-200 font-mono">${value}${unit}</span></div>`;

    let diff = parseFloat(value) - parseFloat(contextValue);
    let comparisonText = diff > 0 ? 'Higher than avg' : 'Lower than avg';
    let comparisonColor = diff > 0 ? 'text-warren-warning' : 'text-warren-success';

    return `
    <div class="flex justify-between items-center text-sm">
        <span class="text-gray-500">${labelHtml}</span>
        
        <span class="relative group cursor-help">
            <span class="text-gray-200 font-mono border-b border-dotted border-gray-600 group-hover:border-warren-accent transition-colors">${value}${unit}</span>
            
            <div class="absolute bottom-full right-0 mb-2 w-48 p-3 bg-gray-900 ring-1 ring-white/10 text-xs text-gray-300 rounded-lg shadow-2xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50 text-right">
                <div class="text-[10px] uppercase tracking-wider text-gray-500 font-bold mb-1">Industry Standard</div>
                <div class="flex justify-end items-baseline gap-2">
                    <span class="text-white font-mono font-bold text-sm">${contextValue}${unit}</span>
                    <span class="text-[10px] text-gray-400">Avg</span>
                </div>
                <div class="mt-1 pt-1 border-t border-gray-800 text-[10px] ${comparisonColor}">
                    ${comparisonText}
                </div>
                <div class="absolute -bottom-1 right-3 w-2 h-2 bg-gray-900 border-r border-b border-gray-700/50 transform rotate-45"></div>
            </div>
        </span>
    </div>
    `;
};

export const linkTV = (symbol) => {
    if (!symbol) return '';
    const cleanSymbol = symbol.split(' ')[0].replace(/[^a-zA-Z]/g, '');
    return `
        <div class="inline-flex items-center gap-1 group/ticker">
            <a href="https://www.tradingview.com/symbols/${cleanSymbol}/" target="_blank" class="font-bold hover:text-warren-accent underline decoration-dotted transition-colors" title="View on TradingView">${symbol}</a>
            <div class="flex gap-1 opacity-0 group-hover/ticker:opacity-100 transition-opacity">
                <button onclick="if(window.openTradeModal) window.openTradeModal('${cleanSymbol}')" class="text-[10px] bg-green-500/10 text-green-400 hover:bg-green-500/20 px-1 rounded border border-green-500/30" title="Paper Trade">⚡</button>
                <button onclick="window.switchTab('research'); window.loadResearch('${cleanSymbol}')" class="text-[10px] bg-warren-accent/10 text-warren-accent hover:bg-warren-accent/20 px-1 rounded border border-warren-accent/30 flex items-center gap-1" title="Institutional Deep Research">
                    <span class="text-[8px] font-black uppercase">Research</span> 🔍
                </button>
            </div>
        </div>
    `;
};
